### ISSUE TITLE
Word list name pls

### ISSUE THREAD

**Issue by vishwa6184** [SamueleAmato/Instagram-Brute-force-2022#1]
Hey, 
I installed it successfully in termux
But I don't know the word list name 
Pls help

**Comment by s4ch4q** [comment]
I think you need to create your own list

**Comment by KalyWareSEC** [comment]
you have to create it yourself. I don't know what you will use it for, but it is usually custom made, you can do it with cupp or elpscrk

**Comment by SamueleAmato** [comment]
defoults word list is named with "wl.txt" but it is empty, either copy paste from another worldlist or import any one you like
